version: '3'
services:
  flask:
    build: ./app
    container_name: steglove-api
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 wsgi:app --reload
