services:
  flask:
    build: ./app
    container_name: steglove
    environment:
      - PYTHONUNBUFFERED=True
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "127.0.0.1:5000:5000"
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 wsgi:app --reload
